# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.6.3) on: dom 25. Set 23:47:04 2011
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile_0xE4DE5D27.mk
#  Part of     : ReefLog
#  Description : This file is used to call necessary targets on wrapper makefile
#                during normal Symbian build process.
#  Version     : 
#
# ==============================================================================



MAKE = make

VISUAL_CFG = RELEASE
ifeq "$(CFG)" "UDEB"
VISUAL_CFG = DEBUG
endif

do_nothing :
	@rem do_nothing

MAKMAKE: create_temps pre_targetdeps store_build

LIB: create_temps pre_targetdeps store_build

BLD: create_temps pre_targetdeps store_build

ifeq "$(PLATFORM)" "WINSCW"
CLEAN: extension_clean winscw_deployment_clean deployment_clean
else
CLEAN: extension_clean deployment_clean
endif

CLEANLIB: do_nothing

RESOURCE: do_nothing

FREEZE: do_nothing

SAVESPACE: do_nothing

RELEASABLES: do_nothing

ifeq "$(PLATFORM)" "WINSCW"
FINAL: finalize winscw_deployment deployment
else
FINAL: finalize deployment
endif

pre_targetdeps : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" pre_targetdeps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

create_temps : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" create_temps QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

extension_clean : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" extension_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

finalize : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" finalize QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment_clean : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" winscw_deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

winscw_deployment : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" winscw_deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

deployment_clean : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" deployment_clean QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

deployment : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" deployment QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)

store_build : d:\Projectos\reeflog\Symbian\src\reeflog\Makefile
	-$(MAKE) -f "d:\Projectos\reeflog\Symbian\src\reeflog\Makefile" store_build QT_SIS_TARGET=$(VISUAL_CFG)-$(PLATFORM)


